const JWT = require('jsonwebtoken')
const User = require("../models/user.model")
const Token = require("../models/token.model")
const sendEmail = require("../utils/email/sendEmail")
const crypto = require("crypto")
const bcrypt = require("bcrypt")